export const T: Record<string, Record<string, string>> = {
  English: {
    expression: "Expression",
    variable: "Variable",
    solve: "Solve",
    examples: "Examples",
    powered: "Powered by SymPy",
    mathSolver: "Math Solver",
    "click to retry": "Click to retry",
    "LLaMA 3 is thinking...": "LLaMA 3 is thinking...",
    "Generate GATE Question": "Generate GATE Question",
    "Full Test Generator": "Full Test Generator",
    "Interview Question Generator": "Interview Question Generator",
    "Performance Analytics": "Performance Analytics",
    Dashboard: "Dashboard",
    "GATE Questions": "GATE Questions",
    "Full Test": "Full Test",
    "Interview Prep": "Interview Prep",
    Analytics: "Analytics",
    "Math Solver": "Math Solver",
    Subject: "Subject",
    Topic: "Topic",
    Language: "Language",
    "Include Audio": "Include Audio",
    "Select a topic and generate!": "Select a topic and generate!",
    "✨ Generate Question": "✨ Generate Question",
    "Difficulty Level": "Difficulty Level",
    "Question Type": "Question Type",
    "Select your answer": "Select your answer",
    "Show Model Answer": "Show Model Answer",
    "Hide Model Answer": "Hide Model Answer",
    Copy: "Copy",
    Download: "Download",
    "Test Duration": "Test Duration",
    "Powered by LLaMA 3 + AMD": "Powered by LLaMA 3 + AMD",
    "Choose your duration!": "Choose your duration!",
    "Generate Test Paper": "Generate Test Paper",
    Role: "Role",
    Domain: "Domain",
    "Popular Roles": "Popular Roles",
  },
  Hindi: {
    expression: "व्यंजक",
    variable: "चर",
    solve: "समाधान",
    examples: "उदाहरण",
    powered: "SymPy द्वारा संचालित",
    mathSolver: "गणित हलकर्ता",
    "click to retry": "पुनः प्रयास करने के लिए क्लिक करें",
    "LLaMA 3 is thinking...": "LLaMA 3 सोच रहा है...",
    "Generate GATE Question": "GATE प्रश्न बनाएँ",
    "Full Test Generator": "पूर्ण टेस्ट जनरेटर",
    "Interview Question Generator": "साक्षात्कार प्रश्न जनरेटर",
    "Performance Analytics": "प्रदर्शन विश्लेषण",
    Dashboard: "डैशबोर्ड",
    "GATE Questions": "GATE प्रश्न",
    "Full Test": "पूर्ण परीक्षण",
    "Interview Prep": "साक्षात्कार तैयारी",
    Analytics: "विश्लेषण",
    "Math Solver": "गणित हलकर्ता",
    Subject: "विषय",
    Topic: "विषय-वस्तु",
    Language: "भाषा",
    "Include Audio": "ऑडियो शामिल करें",
    "Select a topic and generate!": "एक विषय चुनें और उत्पन्न करें!",
    "✨ Generate Question": "✨ प्रश्न उत्पन्न करें",
    "Difficulty Level": "कठिनाई स्तर",
    "Question Type": "प्रश्न प्रकार",
    "Select your answer": "अपना उत्तर चुनें",
    "Show Model Answer": "मॉडल उत्तर दिखाएँ",
    "Hide Model Answer": "मॉडल उत्तर छिपाएँ",
    Copy: "कॉपी",
    Download: "डाउनलोड",
    "Test Duration": "परीक्षा अवधि",
    "Powered by LLaMA 3 + AMD": "LLaMA 3 + AMD द्वारा समर्थित",
    "Choose your duration!": "अपनी अवधि चुनें!",
    "Generate Test Paper": "परीक्षा पत्र उत्पन्न करें",
    Role: "भूमिका",
    Domain: "डोमेन",
    "Popular Roles": "लोकप्रिय भूमिकाएँ",
  }
};

export function t(lang: string, key: string) {
  return T[lang]?.[key] || key;
}
